/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla wordpress.XCTDemoTable
DROP TABLE IF EXISTS `XCTDemoTable`;
CREATE TABLE IF NOT EXISTS `XCTDemoTable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(80) DEFAULT NULL,
  `description` text,
  `date_add` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `active` tinyint(1) unsigned DEFAULT '0',
  `typeid` tinyint(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=84 DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla wordpress.XCTDemoTable: 60 rows
DELETE FROM `XCTDemoTable`;
/*!40000 ALTER TABLE `XCTDemoTable` DISABLE KEYS */;
INSERT INTO `XCTDemoTable` (`id`, `title`, `description`, `date_add`, `active`, `typeid`) VALUES
	(5, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(6, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 1),
	(11, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(13, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(14, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(15, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(16, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(17, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(18, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(19, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(20, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(21, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(22, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(23, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(24, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(25, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(26, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(27, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(28, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(29, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(30, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(31, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(32, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(33, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(34, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(35, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(36, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(37, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(38, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(39, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(40, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(41, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(42, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(43, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(44, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(45, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(46, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(47, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(48, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(49, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(50, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(51, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(52, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(53, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(54, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(55, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(56, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(57, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(58, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(59, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(60, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(61, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(62, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(63, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(64, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(65, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2),
	(66, 'Donec laoreet porttitor imperdiet', 'Donec laoreet porttitor imperdiet. Vivamus pulvinar quis lectus nec commodo. Maecenas luctus vitae purus vitae euismod. Donec finibus, purus ut semper hendrerit, sem nulla faucibus turpis, eu ullamcorper justo enim sit amet nunc. Proin quis erat tincidunt', '2015-06-22 19:08:08', 0, 5),
	(67, 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nis', 'Cras eget ipsum sed orci rutrum lobortis eu sit amet nisl. Quisque non libero ac lorem molestie volutpat eget et velit. Sed tempor commodo tincidunt. Curabitur at elit condimentum purus pellentesque vehicula. Praesent maximus malesuada orci vel mollis.', '2013-04-08 03:03:03', 0, 2),
	(68, 'Etiam volutpat nisl at dolor placerat tempor', 'Etiam volutpat nisl at dolor placerat tempor. Suspendisse aliquet nunc ac magna vulputate, sed venenatis enim convallis. Cras dictum efficitur congue. Cras sit amet facilisis leo. Praesent aliquam tortor augue, at egestas velit rhoncus eu. Quisque ultrice', '2011-09-08 02:39:33', 0, 4),
	(69, 'Phasellus ligula arcu, ultricies et pulvinar eu', 'Phasellus ligula arcu, ultricies et pulvinar eu, tincidunt nec nisi. Suspendisse pulvinar ut justo in eleifend. Nulla imperdiet nibh vel augue molestie pharetra. Aenean nec libero vitae nisi elementum eleifend. Aliquam eu dui ex. Vestibulum id convallis s', '2013-02-01 05:10:16', 1, 2);
/*!40000 ALTER TABLE `XCTDemoTable` ENABLE KEYS */;


-- Volcando estructura para tabla wordpress.XCTDemoTableTypes
DROP TABLE IF EXISTS `XCTDemoTableTypes`;
CREATE TABLE IF NOT EXISTS `XCTDemoTableTypes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla wordpress.XCTDemoTableTypes: 5 rows
DELETE FROM `XCTDemoTableTypes`;
/*!40000 ALTER TABLE `XCTDemoTableTypes` DISABLE KEYS */;
INSERT INTO `XCTDemoTableTypes` (`id`, `description`) VALUES
	(1, 'Type 1'),
	(2, 'Type 2'),
	(3, 'Type 3'),
	(4, 'Another type'),
	(5, 'Custom Type');
/*!40000 ALTER TABLE `XCTDemoTableTypes` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

